version: "3"
services:
 ads-app:
  build: .
  command: ["npm", "start"]
  ports:
   - 3001:3001
  environment:
   PORT: 3001
   MONGODB_URI: mongodb://mongo:27017/db   
  volumes:
   - .:/ads-app
  depends_on: 
   - mongo
  networks: 
    - backend

 mongo:
  image: mongo
  restart: always
  volumes: 
   - ./data:/data/db
  networks: 
   - backend
networks: 
  backend:
