version: "3"
services:
 ads-app:
  build: .
  network_mode: host
  ports:
   - 3001:3001
  environment:
   PORT: 3001
   MONGODB_URI: mongodb://127.0.0.1:27017/db   
  volumes:
   - .:/ads-app
  depends_on: 
   - mongo

 mongo:
  image: mongo
  restart: always
  network_mode: host
  ports: 
   - "27017:27017"
